# PostgreSQL Helm values
# Usage: helm install postgres bitnami/postgresql -n fraud-detection -f k8s/postgres-values.yaml
#use for learning K8s only, not for production. For production, use a managed database service like AWS RDS or GCP Cloud SQL.
auth:
  postgresPassword: "1234"
  username: "admin"
  password: "1234"
  database: "fraud_detection"

primary:
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  persistence:
    size: 10Gi
  initdb:
    scriptsConfigMap: postgres-init

metrics:
  enabled: true  # Prometheus metrics for DB monitoring
