apiVersion: v1
kind: Service
metadata:
  name: fraud-api
  namespace: fraud-detection
  labels:
    app: fraud-api
spec:
  type: ClusterIP
  selector:
    app: fraud-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
