apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-config
  namespace: fraud-detection
data:
  MODEL_PATH: "models:/fraud_detector/Production"
  MLFLOW_TRACKING_URI: "http://mlflow.fraud-detection.svc:5000"
  FRAUD_THRESHOLD: "0.5"
  LOG_LEVEL: "INFO"
  KAFKA_BOOTSTRAP_SERVERS: "kafka.fraud-detection.svc:9092"
  KAFKA_POLL_INTERVAL: "10"
  APP_NAME: "Fraud Detection API"
  APP_VERSION: "1.0.0"
  POSTGRES_DB: "fraud_detection"
